---
- hosts: node1
  become: true
  tasks:
    - name: Install python PIP
      yum:
        name: python-pip
        state: present
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present