---
- name: Create directory for backup cms files
  file:
    path: /data/docker/backup/cms_files
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create directory for backup db files
  file:
    path: /data/docker/backup/db
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Sync files
  shell: rsync -avH /data/docker/cmsfiles/ /data/docker/backup/cms_files/

- name: Stop docker
  shell: docker stop WordPress
  args:
    chdir: /data/docker

- name: Remove docker
  shell: docker rm WordPress

- name: Copy docker-compose file to docker directory
  copy:
    src: /var/lib/jenkins/workspace/update_application/docker-compose_update.yaml
    dest: /data/docker
    owner: root
    group: root
    mode: 0644

- name: Run docker-compose up
  shell: docker-compose -f docker-compose_update.yaml up -d
  args:
    chdir: /data/docker

- name: Pause for runing app
  pause:
    seconds: 40

- name: Curl and check output
  block:
    - name: Curl content
      uri:
        url: "http://192.168.100.11:8080"
        return_content: yes
      register: content
      failed_when: "'WordPress' not in content.content"
    - name: Print content
      debug:
        msg: "{{ content }}"

- name: Rollback to previous version app
  include_role:
    name: rollback